name: Deploy CDK Stack

on:
  push:
    branches:
      - main
      - staging
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Map 'main' branch to 'production' environment, else use branch name
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Bootstrap CDK (idempotent)
        run: |
          npx cdk bootstrap || echo "CDK bootstrap may already be complete. Continuing..."

      - name: Deploy CDK stack
        run: |
          # Use 'production' prefix for main branch, else use branch name
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            STACK_NAME="production-entix-infra"
          else
            STACK_NAME="${GITHUB_REF_NAME}-entix-infra"
          fi
          npx cdk deploy "$STACK_NAME" --require-approval never
